App\Security\User\Infrastructure\Entity\User:
  attributes:
    normalization_context:
      groups: ['user_read']
    denormalization_context:
      groups: ['user_write']
  collectionOperations:
    get:
      method: 'GET'
    post:
      method: 'POST'
  itemOperations: []